### ISSUE TITLE
configurable delimiter 

### ISSUE THREAD

**Issue by frakman1** [ralcr/Jit#6]
> To create a local branch named "AA-55_Blah_blah_blah" for this task you'd do:

What if I want a `:` after the JIRA ID? So instead of 
`AA-55_Blah_blah_blah`

`I want 

`AA-55 : Blah_blah_blah`

I should be able to configure what delimiter I want from a top-level configuration file.

**Comment by cristibaluta** [comment]
Hi, you are not allowed to do that because git itself will not allow branches with spaces. ':' i must confess i don't know if is allowed or not. I was just reading that alt+space is an invisible character and should work. If you run jit setup you can set the separator in the last step, i recommend - or _ but there's no restriction. A different separator between id and name is not possible yet, but looks like an extra complication.
